"""Tests for the AI Interview Agent.

Run:  .venv/Scripts/python.exe test_api.py

Part 1 — Planner compliance (no server needed):
    every candidate gets >= 8 questions across >= 4 distinct curriculum days.

Part 2 — Full API contract (spawns uvicorn, simulates real interviews):
    * POST /api/interview start & turn flow
    * >= 8 questions asked, >= 4 distinct days (verified via /state)
    * structured feedback matching the spec schema at the end
    * error handling: unknown session, bad body, duplicate session
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Dict, List, Optional

PORT = 8123
BASE = f"http://127.0.0.1:{PORT}"

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

from interview_agent.candidate_profile import build_profile          # noqa: E402
from interview_agent.data_loader import load_candidates, load_curriculum  # noqa: E402
from interview_agent.engine import InterviewSession  # noqa: E402
from interview_agent.planner import build_plan, plan_stats, verify_plan_for_all_candidates  # noqa: E402

PASSED = 0
FAILED = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASSED, FAILED
    if condition:
        PASSED += 1
        print(f"  [ok]   {name}")
    else:
        FAILED += 1
        print(f"  [FAIL] {name}  {detail}")


# ======================================================================
# Part 1 — planner compliance
# ======================================================================
def test_planner_compliance() -> None:
    print("\n[1] Planner compliance across all candidates")
    curriculum = load_curriculum()
    candidates = load_candidates()
    check(f"loaded {len(candidates)} candidates and {len(curriculum.get('days', []))} curriculum days",
          len(candidates) >= 15 and len(curriculum["days"]) >= 31)

    violations = verify_plan_for_all_candidates(curriculum, candidates)
    check("every candidate: >= 8 questions, >= 4 distinct days", not violations,
          f"violations: {violations}")

    # per-candidate detail + narrative sanity
    for c in candidates:
        profile = build_profile(c, curriculum)
        plan = build_plan(profile)
        stats = plan_stats(plan)
        opener = plan[0]
        check(
            f"{c['member']['id']} {c['member']['name']}: {stats['total_questions']} q / "
            f"{stats['distinct_days']} days / opens with Day {opener['day']}",
            stats["meets_min_questions"] and stats["meets_min_days"],
            json.dumps(stats),
        )


# ======================================================================
# Part 2 — API contract (live server)
# ======================================================================
def _http(method: str, path: str, body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    req = urllib.request.Request(
        BASE + path,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"Content-Type": "application/json"},
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return {"status": resp.status, "body": json.loads(resp.read().decode())}
    except urllib.error.HTTPError as err:
        raw = err.read().decode("utf-8", "replace")
        try:
            return {"status": err.code, "body": json.loads(raw)}
        except json.JSONDecodeError:
            return {"status": err.code, "body": {"raw": raw[:300]}}
    except Exception as exc:  # connection errors etc.
        return {"status": -1, "body": {"error": repr(exc)}}


RICH_ANSWERS = [
    # generic but credible — hits many concept keywords across topics
    "We built it with embeddings generated by sentence transformers, stored the vectors in Chroma, "
    "and queried with cosine similarity. The retrieval layer routed questions between SQL for "
    "structured claims data and vector search for semantic questions, then merged results. "
    "For the LLM part we used a grounded RAG prompt with retrieved context, function calling with "
    "Pydantic validation, and the whole thing was wrapped in a FastAPI backend.",
    "The key decision was architecture. We separated retrieval from generation so we could evaluate "
    "each piece. The agent loop used ReAct style reasoning — the model picked a tool, we executed it, "
    "fed the observation back, and repeated until it had enough context to answer. We added retries, "
    "timeouts, and structured logging to make it reliable in production.",
    "For deployment we containerized the backend with Docker and ran it on Kubernetes with health "
    "checks. We monitored latency and error rates with Prometheus and Grafana. Evaluation was a "
    "benchmark dataset where we measured grounding and consistency, not just whether answers sounded good.",
    "Conversation memory was the hard part. We persisted history per session, summarized long threads "
    "when we approached token limits, and kept the important context like the user's plan selection "
    "throughout. We validated structured outputs with Pydantic before rendering.",
    "Multi-agent made sense for domain specialization. A router agent delegated to specialists for "
    "claims, plans, and general questions. We compared it against a single agent and found the "
    "multi-agent version was worth it for complex queries but pure overhead for simple ones.",
]

WEAK_ANSWER = "I'm not sure, to be honest — we didn't go very deep on that part."


def test_full_interview(candidate: Dict[str, Any], label: str) -> None:
    print(f"\n[2] Full interview — {label} ({candidate['member']['id']})")
    sid = f"test-{candidate['member']['id'].lower()}"

    start = _http("POST", "/api/interview", {"sessionId": sid, "candidate": candidate})
    check("start: 200 with {reply, done:false}", start["status"] == 200 and
          isinstance(start["body"].get("reply"), str) and start["body"]["done"] is False,
          json.dumps(start))
    check("start body: no feedback field while in progress", "feedback" not in start["body"],
          json.dumps(start))

    turn = start["body"]
    plan_size = turn.get("totalQuestions") or 0
    max_q = 0
    turns = 0
    final: Optional[Dict[str, Any]] = None
    answer_i = 0

    while turn["done"] is False and turns < 60:
        max_q = max(max_q, turn.get("questionNumber") or 0)
        body: Dict[str, Any] = {"sessionId": sid}
        body["message"] = RICH_ANSWERS[answer_i % len(RICH_ANSWERS)] if answer_i % 4 != 3 else WEAK_ANSWER
        answer_i += 1
        resp = _http("POST", "/api/interview", body)
        if resp["status"] != 200:
            check(f"turn {turns}: HTTP 200", False, json.dumps(resp))
            break
        turn = resp["body"]
        turns += 1

    final = turn
    check("interview completes with done:true", final["done"] is True,
          f"stopped after {turns} turns, phase={final}")
    check(f">= 8 questions asked (max q#{max_q}, plan {plan_size})",
          max_q >= 8 and plan_size >= 8)
    check("completed with 'Interview completed.'", final["reply"] == "Interview completed.",
          final.get("reply", ""))
    check("final body matches spec shape {reply, done, feedback}",
          set(final.keys()) == {"reply", "done", "feedback"}, json.dumps(final))

    fb = final.get("feedback")
    check("feedback present with spec schema", bool(fb) and
          isinstance(fb.get("summary"), str) and len(fb.get("summary", "")) > 20 and
          isinstance(fb.get("strengths"), list) and isinstance(fb.get("gaps"), list) and
          isinstance(fb.get("next"), list))
    check("feedback arrays populated", bool(fb) and len(fb["strengths"]) >= 1 and
          len(fb["gaps"]) >= 1 and len(fb["next"]) >= 1, json.dumps(fb))

    st = _http("GET", f"/api/interview/{sid}/state")
    check("state endpoint: >= 4 distinct days asked", st["status"] == 200 and
          st["body"].get("distinctDaysAsked", 0) >= 4, json.dumps(st.get("body")))
    check("state endpoint: done", st["status"] == 200 and st["body"].get("done") is True)

    # contract errors
    unknown = _http("POST", "/api/interview", {"sessionId": "does-not-exist", "message": "hi"})
    check("unknown session -> 404", unknown["status"] == 404)
    dup = _http("POST", "/api/interview", {"sessionId": sid, "candidate": candidate})
    check("duplicate start -> 409", dup["status"] == 409)
    bad = _http("POST", "/api/interview", {"sessionId": "x"})
    check("missing candidate+message -> 422", bad["status"] == 422)


def wait_for_server(proc: subprocess.Popen, tries: int = 40) -> bool:
    for _ in range(tries):
        if proc.poll() is not None:
            return False
        try:
            with urllib.request.urlopen(f"{BASE}/api/candidates", timeout=2):
                return True
        except Exception:
            time.sleep(0.5)
    return False


# ======================================================================
# Part 3 — LLM path via a mock OpenAI-compatible server
# ======================================================================


class _MockLLMHandler(BaseHTTPRequestHandler):
    """A tiny OpenAI-compatible /chat/completions mock."""

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        payload = json.loads(self.rfile.read(length).decode())
        system = payload["messages"][0]["content"]
        if "PER-TOPIC ASSESSMENT" in system:
            content = json.dumps({
                "summary": "Mock summary: solid fundamentals with a couple of gaps to close.",
                "strengths": ["Mock strength: retrieval explained clearly.", "Mock strength: agents."],
                "gaps": ["Mock gap: deployment depth."],
                "next": ["Mock next: rebuild the router.", "Mock next: practice MCP.", "Mock next: mock interview."],
            })
        else:
            content = json.dumps({
                "text": "MOCK-LLM: let's dig one level deeper on that.",
                "action": "followup",
                "assessment": "solid",
            })
        body = json.dumps({"choices": [{"message": {"content": content}}]}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):  # silence
        pass


RICH_BLANKET = (
    "We used embeddings and retrieval with Chroma, grounded RAG, function calling with Pydantic, "
    "agents with tools and MCP servers, docker and kubernetes deployment, and prometheus monitoring."
)


def test_empty_candidate_edge() -> None:
    """A candidate with no mission record must not crash the service."""
    print("\n[4] Edge: candidate with no missions")
    curriculum = load_curriculum()
    ghost = {"member": {"id": "CAND-000", "name": "Ghost User", "jobRole": "N/A"},
             "missions": [], "signals": {}}
    session = InterviewSession("ghost", ghost, curriculum, llm=None)
    reply = session.start()
    check("empty candidate starts without crashing", isinstance(reply, str) and len(reply) > 20)
    fb = None
    for _ in range(40):
        reply, done, feedback = session.handle(
            "I built a chatbot that used embeddings, retrieval, and a grounded LLM prompt.")
        if done:
            fb = feedback
            break
    check("empty candidate completes with feedback", fb is not None and fb["gaps"])


def test_llm_path_and_fallback() -> None:
    print("\n[3] LLM path (mock OpenAI-compatible server) + fallback")
    from interview_agent.llm import LLMClient

    curriculum = load_curriculum()
    candidate = load_candidates()[0]

    mock = ThreadingHTTPServer(("127.0.0.1", 0), _MockLLMHandler)
    mock_port = mock.server_address[1]
    thread = threading.Thread(target=mock.serve_forever, daemon=True)
    thread.start()
    try:
        llm = LLMClient(base_url=f"http://127.0.0.1:{mock_port}", model="mock-model")
        session = InterviewSession("llm-test", candidate, curriculum, llm)
        session.start()
        replies: List[str] = []
        fb: Optional[Dict[str, Any]] = None
        for _ in range(50):
            reply, done, feedback = session.handle(RICH_BLANKET)
            replies.append(reply)
            if done:
                fb = feedback
                break
        check("LLM interview completes", fb is not None)
        check("LLM text used in replies", any("MOCK-LLM" in r for r in replies))
        check("LLM feedback used", fb is not None and fb["summary"].startswith("Mock summary"),
              json.dumps(fb))

        # Graceful fallback: point at a dead port, the interview must still complete.
        dead_llm = LLMClient(base_url="http://127.0.0.1:1", model="ghost", timeout=2)
        session2 = InterviewSession("fallback-test", candidate, curriculum, dead_llm)
        session2.start()
        fb2: Optional[Dict[str, Any]] = None
        for _ in range(50):
            reply, done, feedback = session2.handle(RICH_BLANKET)
            if done:
                fb2 = feedback
                break
        check("dead LLM falls back to deterministic engine and completes",
              fb2 is not None and fb2["summary"] and fb2["gaps"])
    finally:
        mock.shutdown()
        mock.server_close()


def main() -> None:
    test_planner_compliance()

    print("\n[4] Starting server for API contract tests…")
    env = dict(os.environ)
    proc = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "main:app", "--host", "127.0.0.1",
         "--port", str(PORT), "--log-level", "warning"],
        cwd=ROOT, env=env,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    try:
        if not wait_for_server(proc):
            print("  ✘ server failed to start")
            sys.exit(1)
        candidates = load_candidates()
        by_id = {c["member"]["id"]: c for c in candidates}
        # a strong candidate, a sparse candidate, a candidate with failures
        for cid in ("CAND-001", "CAND-011", "CAND-010"):
            test_full_interview(by_id[cid], by_id[cid]["member"]["name"])
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except Exception:
            proc.kill()

    test_llm_path_and_fallback()
    test_empty_candidate_edge()

    print(f"\n===== {PASSED} passed, {FAILED} failed =====")
    sys.exit(1 if FAILED else 0)


if __name__ == "__main__":
    main()
